In [1]:
import numpy as np

In [2]:
arr1 = np.array([1,2,3,4,5])
print(arr1)


[1 2 3 4 5]


In [3]:
print(type(arr1))

<class 'numpy.ndarray'>


In [4]:
print(arr1.shape)

(5,)


In [5]:
arr2 = np.array([1,2,3,4,5])
arr2.reshape(1,5) #one row and 5 column

array([[1, 2, 3, 4, 5]])

In [6]:
arr3 = np.array([[3,5,7,8,]])
arr3.shape

(1, 4)

In [7]:
arr4 = np.array([[0,9,7,6],[5,2,8,7]])
print(arr4)
arr4.shape

[[0 9 7 6]
 [5 2 8 7]]


(2, 4)

In [8]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
np.arange(0,12,2)

array([ 0,  2,  4,  6,  8, 10])

In [10]:
np.ones([2,4])

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [11]:
#identity matrix
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [12]:
#attributes
arr5 = np.array([[2,4,6,8],[8,6,4,2]])

print("array:\n",arr5)
print("shape:",arr5.shape)
print("no.of dimension:",arr5.ndim)
print("data type:",arr5.dtype)
print("item size (in bytes):",arr5.itemsize)

array:
 [[2 4 6 8]
 [8 6 4 2]]
shape: (2, 4)
no.of dimension: 2
data type: int64
item size (in bytes): 8


In [13]:
#vectorized operation
arr6 = np.array([1,2,3,4,5])
arr7 = np.array([10,20,20,40,50])

#Element wise
#add
print("add:",arr6+arr7)

#sub
print("sub:",arr6-arr7)

#multiply
print("multiply:",arr6*arr7)

#division
print("divide:",arr6/arr7)

add: [11 22 23 44 55]
sub: [ -9 -18 -17 -36 -45]
multiply: [ 10  40  60 160 250]
divide: [0.1  0.1  0.15 0.1  0.1 ]


In [14]:
#universal function
arr6 = np.array([1,2,3,4,5])

print(np.sqrt(arr6))

print(np.exp(arr6))

print(np.sin(arr6))

print(np.log(arr6))




[1.         1.41421356 1.73205081 2.         2.23606798]
[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]
[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]
[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]
[0.         0.69314718 1.09861229 1.38629436 1.60943791]


In [15]:
#slicing and indexing

arr8 = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print("array:\n",arr8)

array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [18]:
arr8[0][0]
arr8[0:2,2:]

array([[3, 4],
       [7, 8]])

In [18]:
arr8[1:,1:3]

array([[ 6,  7],
       [10, 11]])

In [19]:
arr8[1:,2:]

array([[ 7,  8],
       [11, 12]])

In [20]:
arr8[[0, 2], 1:3]

array([[ 2,  3],
       [10, 11]])

In [21]:
arr8[[0, 2]]

array([[ 1,  2,  3,  4],
       [ 9, 10, 11, 12]])

In [22]:
arr8[ 1:3]

array([[ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [23]:
arr8[[0, 2], 1:3]

array([[ 2,  3],
       [10, 11]])

In [19]:
#modify array elaments
arr8[0,0] = 100
print(arr8)


[[100   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]


In [20]:
arr8[1:] = 100
print(arr8)

[[100   2   3   4]
 [100 100 100 100]
 [100 100 100 100]]


In [21]:
#statistical 
data = np.array([1,2,3,4,5])

mean = np.mean(data)
std_dev = np.std(data)

normalized_data = (data-mean) / std_dev
print("normalized data : ", normalized_data)

normalized data :  [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [22]:
# stats

data = np.array([1,2,3,4,5,6,7,8,9,10])

mean = np.mean(data)
print("mean:",mean)

median = np.median(data)
print("median:",median)

std_dev = np.std(data)
print("standard deviation:",std_dev)

variance = np.var(data)
print("variance:",variance)



mean: 5.5
median: 5.5
standard deviation: 2.8722813232690143
variance: 8.25


In [23]:
#logical operations

data = np.array([1,2,3,4,5,6,7,8,9,10])

data > 5 

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [24]:
#logical operations

data = np.array([1,2,3,4,5,6,7,8,9,10])

data[data > 5 ]

array([ 6,  7,  8,  9, 10])

In [25]:
#logical operations

data = np.array([1,2,3,4,5,6,7,8,9,10])

data [(data>=5) & (data<=8)]

array([5, 6, 7, 8])