In [65]:
def dy_dx(x):
    return 2*x

In [66]:
dy_dx(2)

4

In [67]:
import torch

In [68]:
x = torch.tensor(4.0,requires_grad=True)

In [69]:
x

tensor(4., requires_grad=True)

In [70]:
y = x**2

In [71]:
y

tensor(16., grad_fn=<PowBackward0>)

In [72]:
x.backward()

In [73]:
import math
def dz_dx(x):
    return 2*x*math.cos(x**2)

In [74]:
dz_dx(5)

9.912028118634735

In [75]:
x=torch.tensor(3.0,requires_grad=True)

In [76]:
x

tensor(3., requires_grad=True)

In [77]:
y = x**2
z = torch.sin(y)

In [78]:
y

tensor(9., grad_fn=<PowBackward0>)

In [79]:
z

tensor(0.4121, grad_fn=<SinBackward0>)

In [80]:
z.backward()

In [81]:
x.grad

tensor(-5.4668)

In [82]:
import torch.nn as nn

In [83]:
class Model(nn.Module):
    def __init__(self,new_feature):
        super().__init__()
        self.linear1 = nn.Linear(new_feature,3)
        self.relu = nn.ReLU()
        self.linear2 = nn.Linear(3,1)
        self.sigmoid = nn.Sigmoid()
    def forward(self,feature):
        out=self.linear1(feature)
        out=self.relu(out)
        out=self.linear2(out)
        out=self.sigmoid(out)
        return out


In [84]:
data = torch.rand(10,5)

In [85]:
data.shape

torch.Size([10, 5])

In [86]:
data

tensor([[0.6788, 0.8966, 0.2766, 0.5077, 0.9764],
        [0.4859, 0.7115, 0.4060, 0.1942, 0.6946],
        [0.8099, 0.2238, 0.1853, 0.4988, 0.7618],
        [0.5511, 0.5373, 0.4793, 0.1867, 0.4245],
        [0.6714, 0.3224, 0.9182, 0.9733, 0.2365],
        [0.2014, 0.3728, 0.8265, 0.7784, 0.3414],
        [0.5399, 0.3580, 0.4998, 0.2214, 0.7269],
        [0.2246, 0.4745, 0.3227, 0.4633, 0.3499],
        [0.5529, 0.9705, 0.7714, 0.1512, 0.9704],
        [0.3841, 0.5161, 0.0058, 0.7786, 0.7813]])

In [87]:
model = Model(data.shape[1])


In [88]:
model(data)

tensor([[0.5309],
        [0.5364],
        [0.5213],
        [0.5150],
        [0.5195],
        [0.5603],
        [0.5322],
        [0.5593],
        [0.5459],
        [0.5596]], grad_fn=<SigmoidBackward0>)

In [89]:
model.forward(data)

tensor([[0.5309],
        [0.5364],
        [0.5213],
        [0.5150],
        [0.5195],
        [0.5603],
        [0.5322],
        [0.5593],
        [0.5459],
        [0.5596]], grad_fn=<SigmoidBackward0>)

In [90]:
model.linear1.weight

Parameter containing:
tensor([[ 0.3762,  0.0010,  0.0175, -0.2093, -0.4052],
        [-0.2430, -0.4348, -0.2715,  0.1924,  0.1194],
        [ 0.3845, -0.3829, -0.1378,  0.0161,  0.0809]], requires_grad=True)

In [91]:
model.linear2.weight

Parameter containing:
tensor([[-0.4622,  0.4269, -0.4570]], requires_grad=True)

In [92]:
model.linear1.bias

Parameter containing:
tensor([0.1217, 0.4101, 0.1658], requires_grad=True)

In [93]:
model.linear2.bias

Parameter containing:
tensor([0.1842], requires_grad=True)

In [94]:
#sequential wrap

class model(nn.Module):
    def __init__(self,num_features):
        super().__init__()
        super.network = nn.Sequential(
            nn.Linear(num_features,3),
            nn.ReLU(),
            nn.Linear(3,1),
            nn.Sigmoid()
        )
    def forward(self,features):
        out = self.network(features)

        return out

In [95]:
data = torch.rand(10,5)

In [96]:
from torchinfo import summary

In [97]:
model = Model(data.shape[1])


In [98]:
summary(model, input_size=(10, 5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 3]                   18
├─ReLU: 1-2                              [10, 3]                   --
├─Linear: 1-3                            [10, 1]                   4
├─Sigmoid: 1-4                           [10, 1]                   --
Total params: 22
Trainable params: 22
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00