In [3]:
print("ishtiyaq")

ishtiyaq


In [5]:
import torch

In [6]:
torch.__version__

'2.5.1+cpu'

In [7]:
if torch.cuda.is_available():
    print("cuda")
else:
    print("nope")

nope


In [8]:
torch.empty(2,4)

tensor([[-1.5366e+03,  1.9997e-42,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00]])

In [9]:
a  =  torch.empty(2,4)

In [10]:
type(a)

torch.Tensor

In [11]:
a.fill_(1)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [12]:
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [13]:
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [14]:
# Create a tensor filled with sevens
tensor_sevens = torch.full((3, 3), 7)  # Example with a 3x3 tensor
print(tensor_sevens)


tensor([[7, 7, 7],
        [7, 7, 7],
        [7, 7, 7]])


In [15]:
torch.rand(2,5)

tensor([[0.0123, 0.2080, 0.7669, 0.9319, 0.6853],
        [0.0227, 0.3028, 0.4055, 0.0043, 0.3035]])

In [16]:
#to get the same matrix values everytime
torch.manual_seed(8)
torch.rand(2,2)

tensor([[0.5979, 0.8453],
        [0.9464, 0.2965]])

In [17]:
torch.manual_seed(8)
torch.rand(2,2)

tensor([[0.5979, 0.8453],
        [0.9464, 0.2965]])

In [18]:
#custom tensor
torch.tensor([[1,2,3],[7,8,9]])

tensor([[1, 2, 3],
        [7, 8, 9]])

In [19]:
torch.arange(11)

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [20]:
torch.arange(1,13,3)

tensor([ 1,  4,  7, 10])

In [21]:
torch.linspace(0,10,20)

tensor([ 0.0000,  0.5263,  1.0526,  1.5789,  2.1053,  2.6316,  3.1579,  3.6842,
         4.2105,  4.7368,  5.2632,  5.7895,  6.3158,  6.8421,  7.3684,  7.8947,
         8.4211,  8.9474,  9.4737, 10.0000])

In [22]:
#identical matrix
torch.eye(4)

tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])

In [23]:
torch.full((3,3),4)

tensor([[4, 4, 4],
        [4, 4, 4],
        [4, 4, 4]])

In [24]:
torch.tensor([[1,2,3],[3,4,5]])

tensor([[1, 2, 3],
        [3, 4, 5]])

In [25]:
x = torch.tensor([[1,2,3],[3,4,5]])

In [26]:
x.shape

torch.Size([2, 3])

In [27]:
torch.empty_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [28]:
torch.rand_like(x,dtype=torch.float32)

tensor([[0.5138, 0.6443, 0.8991],
        [0.0141, 0.5785, 0.1218]])

In [29]:
x+2

tensor([[3, 4, 5],
        [5, 6, 7]])

In [30]:
x*3

tensor([[ 3,  6,  9],
        [ 9, 12, 15]])

In [31]:
x/3

tensor([[0.3333, 0.6667, 1.0000],
        [1.0000, 1.3333, 1.6667]])

In [32]:
c = torch.tensor([1,-2,3,-4])

In [33]:
torch.abs(c)

tensor([1, 2, 3, 4])

In [34]:
torch.neg(c)

tensor([-1,  2, -3,  4])

In [35]:
d = torch.tensor([3.4,4.7,6.8])

In [36]:
torch.round(d)

tensor([3., 5., 7.])

In [37]:
torch.floor(d)

tensor([3., 4., 6.])

In [38]:
torch.ceil(d)

tensor([4., 5., 7.])

In [39]:
e = torch.randint(size=(2,3),low=0,high=10,dtype=torch.float32)

In [40]:
e


tensor([[8., 9., 3.],
        [8., 7., 9.]])

In [41]:
torch.sum(e)

tensor(44.)

In [42]:
torch.sum(e,dim=0)

tensor([16., 16., 12.])

In [43]:
torch.sum(e,dim=1)

tensor([20., 24.])

In [44]:
torch.mean(e)

tensor(7.3333)

In [45]:
torch.min(e)

tensor(3.)

In [46]:
torch.max(e)

tensor(9.)

In [47]:
#index of max
torch.argmax(e)

tensor(1)

In [48]:
#index of min
torch.argmin(e)

tensor(2)

In [50]:
f = torch.randint(size=(2,3),low = 0 , high = 10)
g = torch.randint(size=(3,2),low = 0, high = 10)

In [51]:
f

tensor([[2, 3, 0],
        [5, 7, 7]])

In [52]:
g

tensor([[7, 3],
        [2, 9],
        [0, 4]])

In [53]:
#matrix multiplication fxg 
torch.matmul(f,g)

tensor([[ 20,  33],
        [ 49, 106]])

In [54]:
vector1 = torch.tensor([1,2])
vector2 = torch.tensor([3,4])

In [55]:
vector1

tensor([1, 2])

In [56]:
vector2

tensor([3, 4])

In [57]:
torch.dot(vector1,vector2)

tensor(11)

In [59]:
#rows to columns
torch.transpose(f,0,1)

tensor([[2, 5],
        [3, 7],
        [0, 7]])

In [61]:
h = torch.randint(size=(3,3),low = 0 , high = 10,dtype=torch.float32)

In [62]:
h


tensor([[2., 9., 2.],
        [7., 5., 0.],
        [5., 3., 5.]])

In [63]:
torch.inverse(h)

tensor([[-9.1575e-02,  1.4286e-01,  3.6630e-02],
        [ 1.2821e-01, -3.5479e-09, -5.1282e-02],
        [ 1.4652e-02, -1.4286e-01,  1.9414e-01]])

In [64]:
torch.log(h)

tensor([[0.6931, 2.1972, 0.6931],
        [1.9459, 1.6094,   -inf],
        [1.6094, 1.0986, 1.6094]])

In [65]:
torch.exp(h)

tensor([[7.3891e+00, 8.1031e+03, 7.3891e+00],
        [1.0966e+03, 1.4841e+02, 1.0000e+00],
        [1.4841e+02, 2.0086e+01, 1.4841e+02]])

In [66]:
torch.softmax(h,0)

tensor([[0.0059, 0.9796, 0.0471],
        [0.8756, 0.0179, 0.0064],
        [0.1185, 0.0024, 0.9465]])